DROP DATABASE grysteam;
CREATE DATABASE GrySteam;
CREATE TABLE Gry (IDgry INT, Nazwa VARCHAR(30));
LOAD DATA INFILE '/home/Karol/MalpkaJS/api.steampowered.com.csv' INTO TABLE Gry FIELDS TERMINATED BY ',' IGNORE 1 LINES;
ALTER TABLE Gry ADD COLUMN ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL FIRST;