DROP DATABASE steam_games;
CREATE DATABASE steam_games;
CREATE TABLE Games (SteamID INT, GameName VARCHAR(30));
LOAD DATA INFILE './malpkajs/api.steampowered.com.csv' INTO TABLE Games FIELDS TERMINATED BY ',' IGNORE 1 LINES;
ALTER TABLE Games ADD COLUMN ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL FIRST;